format = """$username$hostname$localip$time$all"""

[username]
style_user = 'white bold'
style_root = 'black bold'
format = '[$user]($style) '
disabled = false
show_always = true

[localip]
ssh_only = false
format = 'from [$localipv4](bold red) '
disabled = false

[time]
disabled = false
time_format = '%D %r EST'

[hostname]
ssh_only = false 
disabled = false
ssh_symbol = " "
format = '@ [$ssh_symbol$hostname]($style) '
